const test=require('node:test'),assert=require('node:assert/strict');
async function fixture(allowed=true){
 const {createOutgoingCalls}=await import('./outgoing-calls.mjs');const calls=[],states=[];let listener,accepted,active;
 class Call{constructor(uid,type){this.uid=uid;this.type=type;}getSessionId(){return 'synthetic';}getCallInitiator(){return{getUid:()=> 'mod'};}getCallReceiver(){return{getUid:()=>this.uid};}getType(){return this.type;}getReceiverType(){return 'user';}}
 const chat={Call,CallListener:class{constructor(x){Object.assign(this,x);}},CALL_STATUS:{CANCELLED:'cancelled'},addCallListener:(id,l)=>listener=l,removeCallListener(){},initiateCall:async c=>{calls.push('initiate');active=c;return c;},rejectCall:async()=>calls.push('cancel'),endCall:async()=>calls.push('end'),getActiveCall:()=>active};
 const controller=createOutgoingCalls({chat,identity:{uid:'mod',role:'moderator'},getSession:async()=>({token:'synthetic',user:{uid:'mod',role:'moderator'}}),authorizeTarget:async t=>{if(!allowed)throw Error('denied');return{actor:{uid:'mod',role:'moderator'},target:{uid:t.uid},roomGuid:t.roomGuid};},onState:s=>states.push(s),onEnded(){},onAccepted:async a=>accepted=a});
 return{controller,calls,states,chat,get listener(){return listener;},get accepted(){return accepted;}};
}
test('verified moderator target rings then accepted provider call yields grant',async()=>{const f=await fixture();await f.controller.start({uid:'student',roomGuid:'room'},'video');assert.deepEqual(f.calls,['initiate']);assert.equal(f.accepted,undefined);await f.listener.onOutgoingCallAccepted(f.chat.getActiveCall());assert.equal((await f.accepted.authorize()).direction,'outgoing');await f.accepted.finish();assert.deepEqual(f.calls,['initiate','end']);f.controller.dispose();});
test('denied target cannot initiate a call',async()=>{const f=await fixture(false);assert.equal(await f.controller.start({uid:'student',roomGuid:'room'},'audio'),false);assert.deepEqual(f.calls,[]);f.controller.dispose();});
test('duplicate start and mismatched acceptance cannot mount call media',async()=>{const f=await fixture();await f.controller.start({uid:'student',roomGuid:'room'},'audio');assert.equal(await f.controller.start({uid:'other',roomGuid:'room'},'audio'),false);await f.listener.onOutgoingCallAccepted(new f.chat.Call('other','audio'));assert.equal(f.accepted,undefined);await f.controller.cancel();assert.deepEqual(f.calls,['initiate','cancel']);f.controller.dispose();});
test('student cannot construct outgoing controller',async()=>{const {createOutgoingCalls}=await import('./outgoing-calls.mjs');assert.throws(()=>createOutgoingCalls({identity:{uid:'student',role:'student'}}));});
